### ISSUE TITLE
Feedback etapa início

### ISSUE THREAD

**Issue by lgnsparda** [laboratorio-de-dinamica-dos-fluidos/2019.2-tubodeventuri#1]
- [x] Os requisitos, escopo e viabilidade do experimento não estão presentes

**Comment by rafaelcarvalho7** [comment]
Desculpa professor, não vimos as tarefas do dia 31/08 por falta de atenção, pensávamos que a próxima etapa já seriam as com as tarefas para o dia 07/09.
